import { SidebarMain } from "@/components/Sidebar-main";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootAccountLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-5">
      <div className="col-span-1 sticky top-0 h-screen">
        <SidebarMain />
      </div>
      <div className="col-span-4 px-5 bg-secondary">{children}</div>
    </div>
  );
}
