import type { Metadata } from "next";
import { Gilroy_Medium, Gilroy_ExtraBold } from "@/fonts";
import "./styles/globals.css";
import { ModalProvider } from "@/hooks/useModal";
import { NotificationProvider } from "@/components/Snackbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Gilroy_Medium.variable} ${Gilroy_ExtraBold.variable} antialiased`}
      >
        <ModalProvider>{children}</ModalProvider>
        <NotificationProvider />
      </body>
    </html>
  );
}
