import type { Metadata } from "next";
import { Gilroy_Medium, Gilroy_ExtraBold } from "@/fonts";
import "./styles/globals.css";
import { ModalProvider } from "@/hooks/useModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=close,menu"
        precedence="default"
      />
      <body
        className={`${Gilroy_Medium.variable} ${Gilroy_ExtraBold.variable} antialiased`}
      >
        <ModalProvider>{children}</ModalProvider>
      </body>
    </html>
  );
}
