import Card from "@/components/Card";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Onboarding - MyJunuvo",
  description: "Generated by create next app",
};

export default function OnBoardingAccountLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex items-center justify-center p-4">
      <div>
        <h1 className="text-2xl font-bold text-center my-5 text-gray-800 tracking-wider">
          KYC UPDATE
        </h1>
        <div className="bg-secondary flex flex-col items-center">
          <Card className="max-w-md">{children}</Card>
        </div>
      </div>
    </div>
  );
}
